#!/usr/bin/env bash
# Bring up local Metabase and mint an API key for the MCP server.
# Idempotent: safe to re-run. Writes credentials to docker/metabase/.env.metabase
# (gitignored). Requires: podman/docker + compose, curl, python3.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$HERE/docker-compose.yml"
ENV_FILE="$HERE/.env.metabase"

MB_URL="${METABASE_URL:-http://localhost:3033}"
ADMIN_EMAIL="${MB_ADMIN_EMAIL:-admin@overslash.local}"
ADMIN_PASSWORD="${MB_ADMIN_PASSWORD:-Overslash123!}"   # >= 6 chars, mixed — Metabase rejects weak/common ones
KEY_NAME="${MB_KEY_NAME:-overslash-mcp}"

# --- pick a compose command --------------------------------------------------
PROJECT="overslash-metabase"
if command -v podman-compose >/dev/null 2>&1; then
  COMPOSE=(podman-compose -p "$PROJECT")
elif docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose -p "$PROJECT")
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose -p "$PROJECT")
else
  echo "ERROR: no podman-compose / docker compose / docker-compose found" >&2
  exit 1
fi

echo "==> Starting Metabase stack (${COMPOSE[*]})"
"${COMPOSE[@]}" -f "$COMPOSE_FILE" up -d

# --- wait for the API to report healthy --------------------------------------
echo -n "==> Waiting for Metabase at $MB_URL (first boot runs DB migrations, ~1-2 min) "
for i in $(seq 1 90); do
  if curl -sf "$MB_URL/api/health" >/dev/null 2>&1; then echo " ready"; break; fi
  echo -n "."
  sleep 5
  if [ "$i" -eq 90 ]; then echo; echo "ERROR: Metabase did not become healthy in time" >&2; exit 1; fi
done

# jq-free JSON field extraction via python3.
jval() { python3 -c 'import sys,json;d=json.load(sys.stdin);print(d'"$1"')' 2>/dev/null; }

# --- obtain an admin session -------------------------------------------------
SETUP_TOKEN="$(curl -sf "$MB_URL/api/session/properties" | jval '.get("setup-token")')"

if [ -n "${SETUP_TOKEN:-}" ] && [ "$SETUP_TOKEN" != "None" ]; then
  echo "==> First-run setup: creating admin $ADMIN_EMAIL"
  SESSION="$(curl -sf -X POST "$MB_URL/api/setup" \
    -H 'Content-Type: application/json' \
    -d @- <<JSON | jval '["id"]'
{
  "token": "$SETUP_TOKEN",
  "user": {
    "first_name": "Local", "last_name": "Admin",
    "email": "$ADMIN_EMAIL", "password": "$ADMIN_PASSWORD",
    "site_name": "Overslash Local"
  },
  "prefs": { "site_name": "Overslash Local", "allow_tracking": false }
}
JSON
)"
else
  echo "==> Already set up: logging in as $ADMIN_EMAIL"
  SESSION="$(curl -sf -X POST "$MB_URL/api/session" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}" | jval '["id"]')"
fi

if [ -z "${SESSION:-}" ] || [ "$SESSION" = "None" ]; then
  echo "ERROR: could not obtain a Metabase session. If you set up Metabase manually," >&2
  echo "       re-run with MB_ADMIN_EMAIL / MB_ADMIN_PASSWORD matching your admin." >&2
  exit 1
fi
AUTH=(-H "X-Metabase-Session: $SESSION")

# --- reuse a working key if we already have one ------------------------------
if [ -f "$ENV_FILE" ]; then
  EXISTING_KEY="$(sed -n 's/^METABASE_API_KEY=//p' "$ENV_FILE" | head -1)"
  if [ -n "${EXISTING_KEY:-}" ] && \
     curl -sf -H "x-api-key: $EXISTING_KEY" "$MB_URL/api/user/current" >/dev/null 2>&1; then
    echo "==> Existing API key in $ENV_FILE still valid — reusing it"
    echo "==> Done. METABASE_URL=$MB_URL"
    exit 0
  fi
fi

# --- find the Administrators group + mint a key ------------------------------
ADMIN_GROUP_ID="$(curl -sf "${AUTH[@]}" "$MB_URL/api/permissions/group" \
  | python3 -c 'import sys,json;print(next(g["id"] for g in json.load(sys.stdin) if g["name"]=="Administrators"))')"

echo "==> Minting API key '$KEY_NAME' (group=$ADMIN_GROUP_ID)"
API_KEY="$(curl -sf -X POST "${AUTH[@]}" "$MB_URL/api/api-key" \
  -H 'Content-Type: application/json' \
  -d "{\"name\":\"$KEY_NAME\",\"group_id\":$ADMIN_GROUP_ID}" | jval '["unmasked_key"]')"

if [ -z "${API_KEY:-}" ] || [ "$API_KEY" = "None" ]; then
  echo "ERROR: failed to mint API key. A key named '$KEY_NAME' may already exist —" >&2
  echo "       delete it in Admin > Settings > API Keys, or set MB_KEY_NAME to a new name." >&2
  exit 1
fi

umask 077
cat > "$ENV_FILE" <<ENV
# Generated by docker/metabase/bootstrap.sh — gitignored, contains a secret.
METABASE_URL=$MB_URL
METABASE_API_KEY=$API_KEY
MB_ADMIN_EMAIL=$ADMIN_EMAIL
MB_ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV

echo "==> Wrote credentials to $ENV_FILE"
echo "==> Metabase UI:  $MB_URL   (login: $ADMIN_EMAIL / $ADMIN_PASSWORD)"
echo "==> Next: ./docker/metabase/register-mcp.sh   to wire up Claude (base repo + all worktrees)"
