// @generated by scripts/gen-service-icons.mjs — do not edit.
// Regenerate with `make service-icons`.
/// Keys with a built-in icon asset — service template keys, plus the `client_*`
/// MCP client marks. An omitted template `icon:` resolves to
/// `builtin:<key>` when the key appears here.
pub const BUILTIN_ICON_SLUGS: &[&str] = &[
    "client_claude",
    "client_cline",
    "client_copilot",
    "client_cursor",
    "client_gemini",
    "client_unknown",
    "client_windsurf",
    "client_zed",
    "deepwiki",
    "email",
    "github",
    "gmail",
    "google_calendar",
    "google_drive",
    "google_keep",
    "google_tasks",
    "http",
    "hubspot",
    "metabase",
    "notion",
    "overslash",
    "resend",
    "stripe",
    "telegram",
    "test_email",
    "whatsapp",
    "x",
];
