// @generated by scripts/gen-service-icons.mjs — do not edit.
// Regenerate with `make service-icons`.
/// Template keys with a built-in icon asset. An omitted `icon:` resolves to
/// `builtin:<key>` when the key appears here.
pub const BUILTIN_ICON_SLUGS: &[&str] = &[
    "deepwiki",
    "email",
    "github",
    "gmail",
    "google_calendar",
    "google_drive",
    "google_keep",
    "google_tasks",
    "hubspot",
    "metabase",
    "notion",
    "overslash",
    "resend",
    "stripe",
    "telegram",
    "test_email",
    "whatsapp",
    "x",
];
